#!/usr/bin/env python3
# Status: production
# Path: imported by — production scripts
"""Scoring — shared veto/gap/early-exit logic.

Single source of truth for both:
  - Cooperative debate (local_debate.py) — multi-round
  - Dawn review pipeline (review_pipeline_steps.py) — single-pass

Confidence-based early exit:
  gap ≤ 5  → high confidence consensus, terminate
  gap ≥ 15 → irreconcilable divergence, terminate
  Otherwise → round threshold: R1≤10, R2≤7, R3=always stop

Veto triggers:
  P_score == 0  → finder produced no valid findings
  R_score == 0  → reflector rejected everything (including real bugs)
  decision == "REJECT" → explicit rejection
"""

from typing import List, Optional

# Dynamic gap thresholds per round
THRESHOLDS = {1: 10, 2: 7}


def check_veto(verdict: dict) -> bool:
    """Server-side veto: P_score==0 or R_score==0 or decision=='REJECT'."""
    p_score = verdict.get("P_score", -1)
    r_score = verdict.get("R_score", -1)
    decision = verdict.get("decision", "")
    return (p_score == 0 or r_score == 0 or decision == "REJECT")


def compute_gap(verdict: dict) -> int:
    """Return abs(P_score - R_score)."""
    p_score = verdict.get("P_score", 0)
    r_score = verdict.get("R_score", 0)
    return abs(p_score - r_score)


def should_continue_round(verdict: dict, round_num: int) -> bool:
    """Confidence-based early exit for multi-round pipelines.

    Returns False when the debate should terminate (consensus or irreconcilable).
    Caller is responsible for logging the reason.
    """
    if round_num >= 3:
        return False

    gap = compute_gap(verdict)

    if gap <= 5:
        return False  # high confidence — caller logs
    if gap >= 15:
        return False  # irreconcilable — caller logs

    threshold = THRESHOLDS.get(round_num, 7)
    return gap <= threshold


def convergence_trend(current_gap: int, prev_gaps: List[int]) -> str:
    """narrowing | stable | diverging | initial."""
    if not prev_gaps:
        return "initial"
    prev = prev_gaps[-1]
    if current_gap < prev:
        return "narrowing"
    if current_gap > prev:
        return "diverging"
    return "stable"


def inject_runtime_metrics(
    verdict: dict, round_num: int, prev_gaps: Optional[List[int]] = None
) -> dict:
    """Server-injected observability metadata. NEVER generated by LLM."""
    gap = compute_gap(verdict)
    threshold = THRESHOLDS.get(round_num, 7)
    return {
        "applied_gap_threshold": threshold,
        "actual_gap": gap,
        "convergence_trend": convergence_trend(gap, prev_gaps or []),
        "should_continue": should_continue_round(verdict, round_num),
        "is_veto": check_veto(verdict),
    }


def next_state_single_pass(verdict: dict) -> str:
    """Single-pass pipeline gating (Dawn etc.).

    No multi-round — instead gates whether to auto-generate diff.

    gap ≤ 10 → diff_generation (auto-approved)
    gap > 10 → manual_review  (flag for human review)
    veto     → manual_review  (unsafe to auto-generate)
    """
    if check_veto(verdict):
        return "manual_review"
    gap = compute_gap(verdict)
    if gap <= THRESHOLDS[1]:  # 10
        return "diff_generation"
    return "manual_review"

